# Generated by Django 2.1.4 on 2018-12-06 01:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('danmu', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='danmumodel',
            name='send_time_float',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
